CREATE DATABASE IF NOT EXISTS nhom14_ui CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE nhom14_ui;

CREATE TABLE IF NOT EXISTS messages (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  topic VARCHAR(255) NOT NULL,
  mkey VARCHAR(255) NULL,
  mvalue LONGTEXT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'queued',
  producer_id VARCHAR(64) NULL,
  partition_id VARCHAR(32) NULL,
  offset_val VARCHAR(32) NULL,
  error TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS consumed_messages (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  topic VARCHAR(255) NOT NULL,
  mkey VARCHAR(255) NULL,
  mvalue LONGTEXT NOT NULL,
  partition_id VARCHAR(32) NULL,
  offset_val VARCHAR(32) NULL,
  consumed_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) NOT NULL,
  customer_name VARCHAR(200),
  total DECIMAL(12,2),
  status VARCHAR(30),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO orders(code, customer_name, total, status) VALUES
('DH001','Nguyen Van A',1990000,'PAID'),
('DH002','Tran Thi B', 2990000,'PENDING')
ON DUPLICATE KEY UPDATE code=VALUES(code);
